// paremeters are nothing but varaiables.tf in terraform
// ansiColor('xterm') --> coloring pluggin
// wait:false means here , sg creation complete aagovargu vpc build mugibeka bedva antha, and if sg build fails , vpc also fails ; since vpc doesnt depend on sg wait is fals ; by default its true

pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select the action for terraform')
    }
    stages {

            // its better not to put apply here for obvious reasons ; this can be used only to check its ability to create infra.
            // when jenkins clones the repo , it will in main page , cd vpc will  take to vpc infra
            
        stage('init and plan') { 
                steps {
                    withAWS(region: 'us-east-1', credentials: 'aws-cred')
                    sh 'cd 1.VPC' 
                    sh 'terraform init -reconfigure'
                    sh 'terraform plan -out expensetf'
                }      
            }
        stage('apply and destroy') {
                steps {     
                    withAWS(region: 'us-east-1', credentials: 'aws-cred')
                    sh """
                    cd 1.VPC
                    if [ ${params.ACTION} == apply ]
                    then
                        terraform apply -auto-approve expensetf
                    else
                        terraform destroy -auto-approve
                    fi
                    """
                }
            }
        stage('triggering SG') {
            when {
                expression{ params.ACTION =='apply' }
            }
                steps {     
                    build job: '2.SG', parameters: [string(name: 'ACTION', value: 'apply')] wait:false
                }
            }   
        }
    post {
        always {
            echo "this section always runs" 
            deleteDir()                     // delete workspace directory after building 
        }
        success {
            echo " this section runs only when pipeline is success"
            echo " this build is due to webhook trigger"
        }
        failure {
            echo "this section runs only when pipeline is failure"
        }

    }
    
}
