// paremeters are nothing but varaiables.tf in terraform
// ansiColor('xterm') --> coloring pluggin
// wait:false means here , sg creation complete aagovargu vpc build mugibeka bedva antha, and if sg build fails , vpc also fails ; since vpc doesnt depend on sg wait is fals ; by default its true

pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select the action for terraform')
    }
    stages {
        stage('init and plan') { 
                steps {
                    withAWS(region: 'us-east-1', credentials: 'aws-cred')
                    sh 'cd 2.SG' 
                    sh 'terraform init -reconfigure'
                    sh 'terraform plan -out expensetf'
                }      
            }
        stage('apply and destroy') {
                steps {     
                    withAWS(region: 'us-east-1', credentials: 'aws-cred')
                    sh """
                    cd 2.SG
                    if [ ${params.ACTION} == apply ]
                    then
                        terraform apply -auto-approve expensetf
                    else
                        terraform destroy -auto-approve
                    fi
                    """
                }
            }
        stage('parallel build') {
            when {
                expression{ params.ACTION =='apply' }
            }
            parallel{
                stage('bastion') {
                    steps {     
                        build job: '3.Bastion', parameters: [string(name: 'ACTION', value: 'apply')] wait:false
                    }
                } 
                stage('eks') {
                    steps {     
                        build job: '4.EKS', parameters: [string(name: 'ACTION', value: 'apply')] wait:false
                    }
                } 
            }   
        }
    }
    post {
        always {
            echo "this section always runs" 
            deleteDir()                     // delete workspace directory after building 
        }
        success {
            echo " this section runs only when pipeline is success"
            echo " this build is due to webhook trigger"
        }
        failure {
            echo "this section runs only when pipeline is failure"
        }

    }
    
}
